apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: nginx
      image: nginx:alpine

      env:
        - name: CONTAINER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: API_KEY

      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets/db-password.txt
          subPath: db-password.txt

  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret
