# ==========================================
# 2. DECLARATIVE SECRET
# ==========================================
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  API_KEY: "super-secret-123"
  db-password.txt: "P@ssword2026!"
